// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6OzHa3My3yp8jc9AxAeuPc0mJWfk34oI',
    appId: '1:202635270387:web:5ea3081be07f1d2794bf86',
    messagingSenderId: '202635270387',
    projectId: 'stone-war',
    authDomain: 'stone-war.firebaseapp.com',
    storageBucket: 'stone-war.firebasestorage.app',
    measurementId: 'G-KRW5P1TSNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSCIQWvOMOMqXPGFyA_K9lbj3jPrdF_xY',
    appId: '1:202635270387:android:9e444e6756c72b8594bf86',
    messagingSenderId: '202635270387',
    projectId: 'stone-war',
    storageBucket: 'stone-war.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5B8zoyDi-S12l3k5Q7SZ9GAAFGoiZKeg',
    appId: '1:202635270387:ios:ddff4e2fd821a88f94bf86',
    messagingSenderId: '202635270387',
    projectId: 'stone-war',
    storageBucket: 'stone-war.firebasestorage.app',
    iosBundleId: 'com.example.stoneWar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5B8zoyDi-S12l3k5Q7SZ9GAAFGoiZKeg',
    appId: '1:202635270387:ios:ddff4e2fd821a88f94bf86',
    messagingSenderId: '202635270387',
    projectId: 'stone-war',
    storageBucket: 'stone-war.firebasestorage.app',
    iosBundleId: 'com.example.stoneWar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6OzHa3My3yp8jc9AxAeuPc0mJWfk34oI',
    appId: '1:202635270387:web:874a87338541239794bf86',
    messagingSenderId: '202635270387',
    projectId: 'stone-war',
    authDomain: 'stone-war.firebaseapp.com',
    storageBucket: 'stone-war.firebasestorage.app',
    measurementId: 'G-MQ7K3K36CF',
  );

}